### ISSUE TITLE
Why there is no info in most tests for cproc and julia?

### ISSUE THREAD

**Issue by rempas** [nordlow/compiler-benchmark#18]
First of all hi and bravo for your amazing work!!! It is very important to have a repo for compiler benchmarks! And you also made a couple of them for every language which is amazing!!!

Now for my question, all the other languages seem to have at least the runtime and compile/build time benchmarks except for cproc and julia which miss almost all the benchmarks. Why is this happening?

**Comment by nordlow** [comment]
The semantic analysis phase (without code-generation and linking) of cproc and julia cannot be executed separately.

**Comment by PallHaraldsson** [comment]
Julia doesn't have a build phase (for Julia programs, yes, for building Julia itself from source), i.e. no separate compilation, by default (can be done though).

I would move "Build Time" numbers for Julia to "Compile Time" column, and but N/A in the former. People may think, correctly, for other languages that the build column has the highest numbers, so for comparison good to be able to scan that column, or sort by, that's the main argument against moving.

**Comment by rempas** [comment]
> 
> 
> The semantic analysis phase (without code-generation and linking) of cproc and julia cannot be executed separately. Julia really only has a build+link+run phase which is the one I benchmark. So I'm cheating a bit and assuming that the build and link phase is much slower than the run-phase.

Interesting! I don't know anything about Julia but why not put the whole compilation process (object files, linking) in the build section for cproc? Also doesn't the runtime means "runtime performance"? Why this can't be measurement for cpoc?

**Comment by nordlow** [comment]
I believe it's more fair to Julia to leave its benchmark in the build column rather than putting it in the compilation column.

**Comment by nordlow** [comment]
I've added Check and Compile op for cproc but disabled Build as I don't have time to look into the linker errors

```
ld: error: unable to find library -l:crt1.o
ld: error: unable to find library -l:crti.o
ld: error: unable to find library -lc
ld: error: unable to find library -l:crtn.o
cproc: link: process 2424876 exited with status 1
```

,

**Comment by rempas** [comment]
> 
> 
> I was wrong about cproc, I think it does have a `Check` phase that avoid code-gen. I've added `Check` and `Compile` op for `cproc` but disabled `Build` at [7fe06ab](https://github.com/nordlow/compiler-benchmark/commit/7fe06ab402570a0e60e3a3962ff9637978ed3d99) as I don't have time to look into the `Build` linker errors
> 
> ```
> ld: error: unable to find library -l:crt1.o
> ld: error: unable to find library -l:crti.o
> ld: error: unable to find library -lc
> ld: error: unable to find library -l:crtn.o
> cproc: link: process 2424876 exited with status 1
> ```
> 
> , Feel free to have a look yourself, @rempas.

How did you passed flags to the LD using cproc? Well you know what? Forget it! I mean, no offense to the cproc developer(s) but they don't even have a proper "--help" message or documentation about how the compiler works so I can't help anyway and you can't either. I will close this issue, once again thanks a lot for the work you are making with those benchmarks! Thanks to you I found out Vox and I like it so far!

**Comment by nordlow** [comment]
You're welcome. :)
