### ISSUE TITLE
Adding extra C compilers

### ISSUE THREAD

**Issue by cyrusmsk** [nordlow/compiler-benchmark#27]
Hi, thanks for the project. Consider to add extra compilers for C: Zig and D.

I've tried to generate C source from your repo (--function-count=200 --function-depth=200).

Then compile it with all available on my system compilers. It seems working, but some issues should be solved (maybe with some additional flags for compiler):
- Zig is very slow at first compilation. Moreover it is caching the results so the next compilation is very fast (some miliseconds).
- It seems Zig makes stripped version by default (which also could take time). Becase it is the only exectubale file that not affected by "strip" command at all - the size is not changing.
- D ImportC compiling your functions, but hardly could be consider as fair-play participant without support of preprocessor. And when I try to add "#include <stdio.h>" - it also gave me an error. So I'm not sure how properly measure lack of this "features".

I've used hyperfine on my Manjaro laptop:
 - AMD Ryzen 3 5300U
 - gcc (GCC) 12.2.0
 - clang version 14.0.6
 - zig 0.9.1
 - DMD64 D Compiler v2.100.2

Results:
Benchmark 1: clang -o code_clang code.c
  Time (abs ≡):         5.034 s               [User: 4.902 s, System: 0.124 s]
 
Benchmark 2: gcc -o code_gcc code.c
  Time (abs ≡):        12.375 s               [User: 12.024 s, System: 0.326 s]
 
Benchmark 3: zig cc -o code_zig code.c
  Time (abs ≡):        70.219 s               [User: 68.940 s, System: 1.083 s]
 
Benchmark 4: dmd -of=code_dmd code.c
  Time (abs ≡):         1.344 s               [User: 1.127 s, System: 0.211 s]
 
Summary
  'dmd -of=code_dmd code.c' ran
    3.75 times faster than 'clang -o code_clang code.c'
    9.21 times faster than 'gcc -o code_gcc code.c'
   52.26 times faster than 'zig cc -o code_zig code.c'

**Comment by Imperatorn** [comment]
Interesting. Thank you for doing these benchmarks!
🇸🇪

**Comment by nordlow** [comment]
> How can dmd be so fast??

Ask Walter bright and start attending DLang confs and meetings.

**Comment by cyrusmsk** [comment]
> > How can dmd be so fast??
> 
> Ask Walter bright and start attending DLang confs and meetings.

Immo was fired from his previous company and now he stopped using D

**Comment by nordlow** [comment]
> Immo was fired from his previous company and now he stopped using D

I have some faith in Zig and Rust aswell.
