### ISSUE TITLE
Question about README note on dmd

### ISSUE THREAD

**Issue by akvadrako** [nordlow/compiler-benchmark#29]
A very nice benchmark. I have a question about this comment in the README:

> The compilers vox dmd are, by a large margin, the fastest. 2 times faster than its closers competitor, tcc.

I don't see how this is true by looking at your table:

| Lang-uage | Check Time [us/fn] | Compile Time [us/fn] | Build Time [us/fn] | Exec Path |
| :--: | :--: | :--: | :--: | :--: |
| Vox | 1.5 (best) | N/A | 5.2 (3.3x) | vox |
| Vox | 2.0 (1.4x) | N/A | 6.1 (3.9x) | vox |
| D | 6.3 (4.2x) | 13.4 (7.4x) | 17.9 (11.4x) | dmd |
| C | 1.8 (1.2x) | 1.8 (best) | 1.6 (best) | tcc |

It seems to me that `tcc` is faster than `dmd`. It's also not clear what Check, Compile and Build time mean.

Is Check about just checking syntax?
How is Build different than Compile?

**Comment by nordlow** [comment]
I just updated the README highlighting the superiority of tcc.
