### ISSUE TITLE
please add cproc for C

### ISSUE THREAD

**Issue by rofl0r** [nordlow/compiler-benchmark#4]
https://github.com/michaelforney/cproc

should be several times faster than GCC.
(of course, if your goal is to make DMD look good, then you probably don't want to add this :-)

**Comment by nordlow** [comment]
Thanks. I'll look into it.

**Comment by nordlow** [comment]
I've built `cproc` using `./configure` and `make`.

But when I build hello world

int main() { return 0; }

as
 
```
./cproc main.c -o main
```

it errros as

```
cproc: codegen: spawn "qbe": No such file or directory
cproc: compile: process signaled: Terminated
cproc: preprocess: process signaled: Terminated
```

**Comment by nordlow** [comment]
I've built `cproc` using `./configure` and `make`.

But when I build hello world

int main() { return 0; }

as
 
```
./cproc main.c -o main
```

it errros as

```
cproc: codegen: spawn "qbe": No such file or directory
cproc: compile: process signaled: Terminated
cproc: preprocess: process signaled: Terminated
```

**Comment by rofl0r** [comment]
you need to run "make qbe" and then put the produced qbe binary in qbe/ into your PATH, then run cproc

cproc executable runs qbe as a subprocess (sorry about that)

**Comment by nordlow** [comment]
That seems awkward. Can you update the Makefile so it supports something along the line

```
make PREFIX=~/local/bin qbe-install
```

**Comment by rofl0r** [comment]
cproc isnt my project, but i contacted its author regarding this. thanks for your patience!

**Comment by nordlow** [comment]
Note that D performs a set of extra semantic passes for instance dead code elimination. So you must take into account all those passes or disable them to get a fair comparison.

**Comment by rofl0r** [comment]
of course: qbe does that too and a lot more. according to its website it's designed to achieve 70% of llvm performance while staying reasonably simple. but since your benchmark focuses on compilation speed, this is where cproc/qbe shine the most: even just compiling cproc itself takes less than one second on my system.

**Comment by nordlow** [comment]
Nice. I'm gonna have look at QBE.

**Comment by nordlow** [comment]
> of course: qbe does that too and a lot more.

Note quite the same. DMD has dead-code elimination in the frontend that signal the user of mistakes in the data flow.

**Comment by nordlow** [comment]
> you need to run "make qbe" and then put the produced qbe binary in qbe/ into your PATH, then run cproc
> 
> cproc executable runs qbe as a subprocess (sorry about that)

I suppose you mean put the `qbe/obj/qbe` into the path.

**Comment by nordlow** [comment]
When I build 

```C
int main(void) { return 0; }
```

as

```
cproc f.c -o f
```

it fails during linking as

```
//usr/lib/x86_64-linux-gnu/crt1.o:function _start: error: undefined reference to 'main'
cproc: link: process 402367 exited with status 1
```

**Comment by nordlow** [comment]
Is there a flag to to perform syntax only like `-fsyntax-only` in GCC?

**Comment by michaelforney** [comment]
Thanks for taking a look at cproc!

I'm not sure what's going wrong during linking. Could you provide your system details, and also the output of `cproc -v f.c -o f`?

> according to its website it's designed to achieve 70% of llvm performance while staying reasonably simple

I think this is more of an aspirational goal, I am not exactly sure how close it is to meeting that goal.

> Is there a flag to to perform syntax only like -fsyntax-only in GCC?

Not currently, no.

**Comment by michaelforney** [comment]
Thinking about -fsyntax-only, I think you could get part of the way there using `-emit-qbe -o /dev/null`. That would still generate QBE IL, but skip running `qbe` itself.

**Comment by nordlow** [comment]
I've added support for cproc in benchmark. However `cproc` hangs (enters an infinte loop?) for

    ./benchmark --languages=C --function-count=20 --function-depth=46 --run-count=1

but not for

    ./benchmark --languages=C --function-count=20 --function-depth=45 --run-count=1

**Comment by nordlow** [comment]
> Thinking about -fsyntax-only, I think you could get part of the way there using `-emit-qbe -o /dev/null`. That would still generate QBE IL, but skip running `qbe` itself.

Seems like a good idea.

**Comment by rofl0r** [comment]
> Update: I've updated now. It runs both a compile to machine code and an emit of qbe.

cool! looking forward to see cproc results in README.md

**Comment by nordlow** [comment]
> > Update: I've updated now. It runs both a compile to machine code and an emit of qbe.
> 
> cool! looking forward to see cproc results in README.md

cproc enters an infinite loop, it seems. See above.

**Comment by michaelforney** [comment]
I'm unable able to reproduce the hang on my system. I will try on ubuntu 20.04, since that is what the install script mentions.

**Comment by nordlow** [comment]
> I'm unable to reproduce the hang on my system. I will try on ubuntu 20.04, since that is what the install script mentions.

Strange. Yes, I'm sitting on Ubuntu 20.04.

**Comment by michaelforney** [comment]
Hmm... I don't seem to be able to reproduce on Ubuntu 20.04 either:
https://builds.sr.ht/~mcf/job/307438

If it's not too much trouble, could you use gdb -p to attach to the hung process and get a backtrace?

**Comment by nordlow** [comment]
Output:

```
Program received signal SIGINT, Interrupt.
0x00007fae918f5dba in wait4 () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) up
#1  0x0000557b8bd6f189 in buildobj (input=0x557b8ca4b820, output=0x557b8ca4b930 "/tmp/cproc-zixpYs") at driver.c:266
266			pid = wait(&status);
(gdb) 
#2  0x0000557b8bd70245 in main (argc=0, argv=0x7fffe67d85e8) at driver.c:573
573			buildobj(input, output);
(gdb) 

```

**Comment by nordlow** [comment]
Hang on...

**Comment by nordlow** [comment]
I had a dirty checkout. Things work now. About twice as fast at building as D.

**Comment by nordlow** [comment]
One thing. cproc forgets to set executable permissions on outputted executable on Linux.

**Comment by michaelforney** [comment]
> One thing. `cproc` forgets to set executable permissions on outputted executable on Linux.

`cproc` just calls the system linker, which should be setting the appropriate executable permissions. I tested lld and GNU ld, and both create a binary with the executable bit set, so I'm not sure why it isn't getting set for you.

**Comment by rofl0r** [comment]
thanks, closing this now as 
https://github.com/nordlow/compiler-benchmark/commit/7f64bbb41a9b32948e608dade4b15b9dabbcb6cb has been committed.
