### ISSUE TITLE
[feature request] Add Nim language

### ISSUE THREAD

**Issue by xflywind** [nordlow/compiler-benchmark#8]
Hi, could you add Nim language?

Nim is a system language using [automatic reference counting with destructors and move semantics](https://nim-lang.org/blog/2020/10/15/introduction-to-arc-orc-in-nim.html) to manage memory. It supports C/C++/JS backends. Nim has a powerful macro system which allows direct manipulation of the AST, offering nearly unlimited opportunities.

The website:
https://nim-lang.org

The Github repo:
https://github.com/nim-lang/Nim

Installation:
https://nim-lang.org/install.html

debug build: `nim c --gc:arc app.nim`
release build: `nim c --gc:arc -d:release app.nim`
check?: `nim check app.nim`

Sample code:
```nim
proc add_long_n0_h0(x: int): int =
  return x + 15440

proc add_long_n0(x: int): int =
  return x + add_long_n0_h0(x) + 95485

proc add_long_n1_h0(x: int): int =
  return x + 37523

proc add_long_n1(x: int): int =
  return x + add_long_n1_h0(x) + 92492

proc add_long_n2_h0(x: int): int =
  return x + 39239

proc add_long_n2(x: int): int =
  return x + add_long_n2_h0(x) + 12248


var long_sum = 0;
long_sum += add_long_n0(0)
long_sum += add_long_n1(1)
long_sum += add_long_n2(2)
```

**Comment by nordlow** [comment]
I'll try.

**Comment by nordlow** [comment]
> Hi, could you add Nim language?
> 
> Nim is a system language using [automatic reference counting with destructors and move semantics](https://nim-lang.org/blog/2020/10/15/introduction-to-arc-orc-in-nim.html) to manage memory. It supports C/C++/JS backends.
> 
> The website:
> https://nim-lang.org
> 
> The Github repo:
> https://github.com/nim-lang/Nim
> 
> Installation:
> https://nim-lang.org/install.html
> 
> debug build: `nim c --gc:arc app.nim`
> release build: `nim c --gc:arc -d:release app.nim`
> check?: `nim check app.nim`
> 
> Sample code:
> 
> ```nim
> proc add_long_n0_h0(x: int): int =
>   return x + 15440
> 
> proc add_long_n0(x: int): int =
>   return x + add_long_n0_h0(x) + 95485
> 
> proc add_long_n1_h0(x: int): int =
>   return x + 37523
> 
> proc add_long_n1(x: int): int =
>   return x + add_long_n1_h0(x) + 92492
> 
> proc add_long_n2_h0(x: int): int =
>   return x + 39239
> 
> proc add_long_n2(x: int): int =
>   return x + add_long_n2_h0(x) + 12248
> 
> 
> var long_sum = 0;
> long_sum += add_long_n0(0)
> long_sum += add_long_n1(1)
> long_sum += add_long_n2(2)
> ```

You can give master a try now.

**Comment by nordlow** [comment]
The flag `--gc:arc` doesn't work on nim version packaged with Ubuntu 20.04 but works with Ubuntu 21.04. Is there a different betweeen `--gc:arc` and `--gc:refc`? I'm gonna use `--gc:refc` for now because it works on Ubuntu 20.04.

**Comment by xflywind** [comment]
> Is there a different betweeen --gc:arc and --gc:refc

refc is the default memory management method. arc is introduced since 1.2.x. 

> You can give master a try now.

Nice, thanks!

**Comment by Yardanico** [comment]
@nordlow 1.0.6 and even 1.2 are quite old releases, it's really preferable to have 1.4

**Comment by xflywind** [comment]
Yeah as @Yardanico suggested, can you use `curl` to install latest Nim?

https://www.osradar.com/nim-programming-language-ubuntu-debian

BTW system is imported implicit, so it is unnecessary to import it.

**Comment by xflywind** [comment]
thanks!
